version: '3.4'

services:
  immongo:
    image: mongo
  
  inmetrics.desafio.lancamento.api:
    image: ${DOCKER_REGISTRY-}desafiofeirasapi
    build:
      context: .
      dockerfile: desafio.feiras.api/Dockerfile